"""empty message

Revision ID: 921614c4b5bf
Revises: 3537f599d1ca
Create Date: 2023-01-27 17:34:39.200064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921614c4b5bf'
down_revision = '3537f599d1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('length', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
